export const GETCATEGORYSUCCESS="GET_CATEGORY_SUCCESS"
export const ACTIVECATEGORY="ACTIVE_CATEGORY"

export const GETSUBCATEGORYSUCCESS="GET_SUBCATEGORY_SUCCESS"
export const ACTIVESUBCATEGORY="ACTIVE_SUBCATEGORY"

export const GETUSERSUCCESS="GET_USER_SUCCESS"
export const ACTIVEUSER="ACTIVE_USER"

export const LOGINSTATUS="LOGIN_STATUS"

export const GETLOGINMODAL ="GET_LOGIN_MODAL"

export const GETREGISTERMODAL ="GET_REGISTER_MODAL"

export const GETMATCHSUCCESS="GET_MATCH_SUCCESS"
export const ACTIVEMATCH="ACTIVE_MATCH"

export const GETMESSAGESUCCESS="GET_MESSAGE_SUCCESS"
export const ACTIVEMESSAGE="ACTIVE_MESSAGE"

export const GETROLESUCCESS="GET_ROLE_SUCCESS"
export const ACTIVEROLE="ACTIVE_ROLE"

export const GETPRODUCTSUCCESS="GET_PRODUCT_SUCCESS"
export const ACTIVEPRODUCT="ACTIVE_PRODUCT"

